name: Deploy Android App on AppCenter
on:
  workflow_call:
    inputs:
      file:
        description: 'The path to the file to be released'
        required: true
        type: string
      name:
        description: 'The name of the app'
        required: true
        type: string
      group:
        description: 'The group that will have access to the version released'
        required: false
        type: string
        default: '"DEV"'
jobs:
  build:
    name: Build .apk file
    runs-on: setup-flutter

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - run: flutter build apk
  Deploy:
    name: Deploy file to AppCenter
    needs: [build]
    runs-on: macos-latest
    steps:
      - name: AppCenter CLI Action
        uses: charliealbright/appcenter-cli-action@v1.0.1
        with:
          token: ${{secrets.APPCENTER_API_TOKEN}}
          command: 'appcenter distribute distribute groups publish -f ${{inputs.file}} --app ${{inputs.name}} --group ${{inputs.group}}'