name: Deploy Android App on AppCenter
on:
  workflow_call:
    inputs:
      file:
        description: 'The path to the file to be released'
        required: true
        type: string
      name:
        description: 'The name of the app'
        required: true
        type: string
      group:
        description: 'The group that will have access to the version released'
        required: false
        type: string
        default: '"DEV"'
jobs:
  build:
    name: Build .apk file
    runs-on: macos-latest

    steps:
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.keystore
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build Android App
        run: |
          flutter build apk --dart-define FLAVOR="${{ github.event.inputs.environment }}"
          ls -la

  Deploy:
    name: Deploy file to AppCenter
    needs: [build]
    runs-on: macos-latest
    steps:
      - name: AppCenter CLI Action
        uses: charliealbright/appcenter-cli-action@v1.0.1
        with:
          token: ${{secrets.APPCENTER_API_TOKEN_ANDROID}}
          command: 'appcenter distribute distribute groups publish -f ${{inputs.file}} --app ${{inputs.name}} --group ${{inputs.group}}'