name: Manual run

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.2'
          channel: 'stable'

      - name: Install pub Dependencies
        run: flutter pub get

      #      - name: Generate JSON serialization code for models
      #        run: flutter pub run build_runner build --delete-conflicting-outputs
      #
      #      - name: Run flutter analyzer
      #        run: flutter analyze
      #
      #      - name: Run Tests
      #        run: flutter test

      - name: Build Android App
        run: |
          flutter build apk --dart-define FLAVOR="${{ github.event.inputs.environment }}"
          ls -la
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: AppCenter CLI Action
        uses: charliealbright/appcenter-cli-action@v1.0.1
        with:
          token: ${{secrets.APPCENTER_API_TOKEN}}
          command: 'appcenter distribute release -f build/app/outputs/flutter-apk/app-release.apk --app trunghv-vbee.ai/APP --group DEV'
      - name: AppCenter CLI Action
        uses: charliealbright/appcenter-cli-action@v1.0.1
        with:
          token: ${{secrets.APPCENTER_API_TOKEN}}
          command: 'appcenter distribute release -f build/ios/iphoneos/app.ipa --app trunghv-vbee.ai/APP --group DEV'